### ISSUE TITLE
"Publish" the Intake Cookbook on the Gallery?

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/intake-cookbook#25]
This Cookbook has some great content, but it's currently hard to find since it doesn't appear on the [Gallery](https://cookbooks.projectpythia.org)

 Should we add it to the Gallery before AGU to bulk up our visible content?

(In my view, "publishing" on the gallery in no way implies that the content is finished and set in stone -- just that it runs and has something potentially useful for readers)

What do you think @jnmorley @jukent?

**Comment by jukent** [comment]
I'm in favor.
