### ISSUE TITLE
Nightly builds failing

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/intake-cookbook#26]
The nightly builds for this cookbook have been failing for the last couple of weeks, e.g. https://github.com/ProjectPythia/intake-cookbook/actions/runs/3717648320/jobs/6305214610

What has changed upstream that triggered the failure?

**Comment by jnmorley** [comment]
I think it is a problem associated with a new version of python. Trying to use the book locally on my computer Jupyter labs would not load, but pinning the python version to 3.8 seems to fix the issue.

**Comment by brian-rose** [comment]
This was fixed in #28, closing now.
